add the option to turn off ticks mirrored
liuyxpp/MakiePublication.jl pull request #15
Opened 2024-08-14 06:48 UTC by phyjswang

Dear Prof. Liu,

Thanks for this wonderful packages!

For the APS theme, `theme.Axis.xticksmirrored` and `theme.Axis.xticksmirrored` are always `true`. But when using left and right yaxis for different quantities, one must turn off this option. Hence I add the option to make them `false` by the key word argument `xticksmirrored=false` and `yticksmirrored=false`.

Best,
Junsen Wang

2024-08-22 02:24 UTC, liuyxpp commented
@phyjswang will you have time to do the revisions? Thanks!

2024-08-22 03:16 UTC, phyjswang reviewed
Ready to be merged.

2024-08-22 07:26 UTC, liuyxpp commented
> Ready to be merged.

Sorry. I am not aware of any new commit addressing the review I made above.

2024-08-22 07:33 UTC, phyjswang commented
> > Ready to be merged.
> 
> Sorry. I am not aware of any new commit addressing the review I made above.

Forgive me for not very familiar with GitHub PR stuffs. What is your review? I do not find it.

2024-11-01 12:49 UTC, liuyxpp requested changes
It would be better if these two options are explicitly listed as keyword args of theme_aps with default value true. Once you make this modification, I will merge the PR. Thanks!

2024-11-05 16:53 UTC, phyjswang commented on src/aps.jl
OK, I've made the changes.

2025-03-11 12:03 UTC, liuyxpp reviewed
I plan to merge this PR. Before that, can I ask why are you restrict Makie to v0.22 and Colors to v0.13? Shall we instead allow both Makie v0.21 and v0.22, Colors v0.12 and v0.13?

2025-05-27 12:56 UTC, phyjswang commented
> I plan to merge this PR. Before that, can I ask why are you restrict Makie to v0.22 and Colors to v0.13? Shall we instead allow both Makie v0.21 and v0.22, Colors v0.12 and v0.13?

There is no particular reason to restrict Makie and Colors to these version. You may freely change these version restrictions.

2025-06-14 08:14 UTC, merged